import importlib.util
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


patch = load_module("patch", ROOT / "patch.py")
sites = load_module("sites", ROOT / "sites.py")

RETAIL = ROOT / "roms" / "dungeon-master-usa.sfc"

SYMBOLS = """; wla symbolic information file
; generated by asar

[labels]
00:FBED b00_first
00:FBF5 b00_feed
00:FBFA b00_drain
04:AA1B b04_0080
04:AA20 b04_0084
04:AA25 b04_0088
04:AA2A b04_008C
9C:E203 dsp_write
9C:E21E dsp_read
9C:E788 :macro_0_feeding
"""


"""The checks that need the cartridge itself.

Nobody may distribute that dump, so on a machine without it every one of
these reports as skipped. They live apart from the rest because a coverage
gate cannot be met by a file whose paths depend on what a machine holds:
one machine runs these and another runs none of them, and no single build
can exercise both.
"""


@unittest.skipUnless(RETAIL.exists(), "the retail dump is supplied by the builder")
class RetailTest(unittest.TestCase):
    def setUp(self):
        self.image = RETAIL.read_bytes()
        self.symbols = patch.resolve(patch.read_symbols(SYMBOLS))

    def test_the_first_port_write_is_the_one_the_boot_code_makes(self):
        first = sites.find(self.image, [sites.KIND_WRITE])[0]

        self.assertEqual((first.bank, first.address), (0x00, 0x801E))

    def test_no_retail_access_survives_the_patch(self):
        result = patch.apply(self.image, self.symbols)

        self.assertEqual(patch.residue(bytes(result)), {})

    def test_the_patched_image_is_the_same_size(self):
        result = patch.apply(self.image, self.symbols)

        self.assertEqual(len(result), len(self.image))

    def test_the_patch_changes_nothing_outside_the_bytes_it_declares(self):
        result = patch.apply(self.image, self.symbols)
        allowed = patch.regions(self.image)
        changed = {
            offset
            for offset, (before, after) in enumerate(zip(self.image, result, strict=True))
            if before != after
        }

        self.assertEqual(changed - allowed, set())

    def test_the_patch_changes_a_byte_of_every_site(self):
        result = patch.apply(self.image, self.symbols)
        found = sites.find(self.image)
        for site in found:
            width = patch.WIDTHS[site.kind]
            before = self.image[site.offset : site.offset + width]
            after = result[site.offset : site.offset + width]

            self.assertNotEqual(before, after, f"site at {site.offset:#x} untouched")


class UnknownSiteTest(unittest.TestCase):
    """A kind nobody wrote a case for is refused rather than passed over.

    Returning the image unchanged would leave that access still pointing at a
    chip the finished cartridge does not have, and nothing downstream would say
    so: the build would succeed and the game would reach for hardware that is
    not there.
    """

    def test_a_site_of_an_unknown_kind_is_refused(self):
        site = sites.Site(kind="something nobody wrote", offset=0, address=0x8000, bank=0)

        with self.assertRaises(patch.UnknownSite):
            patch.rewrite_site(bytearray(16), site, {})

    def test_and_the_refusal_names_the_kind(self):
        site = sites.Site(kind="something nobody wrote", offset=0, address=0x8000, bank=0)

        with self.assertRaises(patch.UnknownSite) as raised:
            patch.rewrite_site(bytearray(16), site, {})

        self.assertIn("something nobody wrote", str(raised.exception))


class SymbolReadingTest(unittest.TestCase):
    """What asar emits is not always a symbol, and the reader says which is which."""

    def test_a_line_with_an_unreadable_address_is_passed_over(self):
        found = patch.read_symbols("zz:zzzz  nonsense\n00:8000  real")

        self.assertNotIn("nonsense", found)
        self.assertEqual(found["real"], (0x00, 0x8000))

    def test_a_comment_is_passed_over(self):
        self.assertEqual(patch.read_symbols("; a comment"), {})

    def test_and_so_is_a_section_heading(self):
        self.assertEqual(patch.read_symbols("[labels]"), {})

    def test_and_a_line_with_no_name_at_all(self):
        self.assertEqual(patch.read_symbols("00:8000"), {})

    def test_and_a_local_label(self):
        self.assertEqual(patch.read_symbols("00:8000 :local"), {})


if __name__ == "__main__":
    unittest.main()
