import importlib.util
import unittest
from pathlib import Path
from typing import Any, override

ROOT = Path(__file__).resolve().parent


def load_module(name: str, path: Path) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None, "no loader for that path"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


patch = load_module("patch", ROOT / "patch.py")
sites = load_module("sites", ROOT / "sites.py")

RETAIL = ROOT / "roms" / "dungeon-master-usa.sfc"

SYMBOLS = """; wla symbolic information file
; generated by asar

[labels]
00:FBED b00_first
00:FBF5 b00_feed
00:FBFA b00_drain
04:AA1B b04_0080
04:AA20 b04_0084
04:AA25 b04_0088
04:AA2A b04_008C
9C:E203 dsp_write
9C:E21E dsp_read
9C:E788 :macro_0_feeding
"""


class SymbolTest(unittest.TestCase):
    def test_a_label_is_read_with_its_bank_and_address(self) -> None:
        found = patch.read_symbols(SYMBOLS)

        self.assertEqual(found["dsp_write"], (0x9C, 0xE203))

    def test_anonymous_macro_labels_are_ignored(self) -> None:
        found = patch.read_symbols(SYMBOLS)

        self.assertNotIn(":macro_0_feeding", found)

    def test_a_file_without_the_labels_it_needs_is_refused(self) -> None:
        with self.assertRaises(patch.MissingSymbol):
            patch.resolve(patch.read_symbols("[labels]\n00:8000 something\n"))

    def test_every_label_the_patch_needs_is_resolved(self) -> None:
        resolved = patch.resolve(patch.read_symbols(SYMBOLS))

        self.assertEqual(sorted(resolved), sorted(patch.REQUIRED))


class EncodingTest(unittest.TestCase):
    def test_a_long_call_carries_its_bank(self) -> None:
        self.assertEqual(patch.long_call(0x9C, 0xE203), bytes([0x22, 0x03, 0xE2, 0x9C]))

    def test_a_long_call_is_the_width_of_the_store_it_replaces(self) -> None:
        self.assertEqual(len(patch.long_call(0x9C, 0xE203)), len(sites.STA_PORT))

    def test_a_near_call_is_the_width_of_the_block_move_it_replaces(self) -> None:
        self.assertEqual(len(sites.call_to(0xFBF5)), len(sites.MVN_TO_PORT))

    def test_the_status_replacement_is_the_width_of_the_poll(self) -> None:
        self.assertEqual(len(patch.STATUS_REPLACEMENT), len(sites.LDA_STATUS))

    def test_the_status_replacement_loads_zero_and_does_nothing_else(self) -> None:
        self.assertEqual(patch.STATUS_REPLACEMENT, bytes([0xA9, 0x00, 0xEA, 0xEA]))


class ApplyTest(unittest.TestCase):
    @override
    def setUp(self) -> None:
        self.symbols = patch.resolve(patch.read_symbols(SYMBOLS))

    def build(self, pieces: Any) -> Any:
        end = max(offset + len(payload) for offset, payload in pieces.items())
        image = bytearray(max(0x28000, end))
        for offset, payload in pieces.items():
            image[offset : offset + len(payload)] = payload
        return bytes(image)

    def test_a_port_write_becomes_a_call_to_the_write_entry(self) -> None:
        image = self.build({0x1000: sites.STA_PORT})

        result = patch.rewrite_site(
            bytearray(image), sites.Site(sites.KIND_WRITE, 0x1000, 0x9000, 0), self.symbols
        )

        self.assertEqual(bytes(result[0x1000:0x1004]), patch.long_call(0x9C, 0xE203))

    def test_the_first_port_write_of_all_initialises_before_it_writes(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x1000: sites.STA_PORT})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x1E:0x22]), patch.long_call(0x00, 0xFBED))
        self.assertEqual(bytes(result[0x1000:0x1004]), patch.long_call(0x9C, 0xE203))

    def test_a_port_read_becomes_a_call_to_the_read_entry(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x2000: sites.LDA_PORT})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x2000:0x2004]), patch.long_call(0x9C, 0xE21E))

    def test_a_status_poll_becomes_a_load_of_zero(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x3000: sites.LDA_STATUS})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x3000:0x3004]), patch.STATUS_REPLACEMENT)

    def test_a_block_move_into_the_port_becomes_a_near_call(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x4000: sites.MVN_TO_PORT})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x4000:0x4003]), sites.call_to(0xFBF5))

    def test_a_block_move_out_of_the_port_becomes_a_near_call(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x4000: sites.MVN_FROM_PORT})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x4000:0x4003]), sites.call_to(0xFBFA))

    def test_a_trampoline_call_is_pointed_at_its_own_stub(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x20000: sites.call_to(0x0084)})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x20000:0x20003]), sites.call_to(0xAA20))

    def test_a_trampoline_call_outside_the_bank_is_left_alone(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x08000: sites.call_to(0x0084)})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x08000:0x08003]), sites.call_to(0x0084))

    def test_the_image_keeps_its_size(self) -> None:
        image = self.build({0x1E: sites.STA_PORT})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(len(result), len(image))

    def test_nothing_outside_a_site_is_touched(self) -> None:
        image = self.build({0x1E: sites.STA_PORT, 0x5000: b"\xde\xad\xbe\xef"})

        result = patch.apply(image, self.symbols, boot_write_offset=0x1E)

        self.assertEqual(bytes(result[0x5000:0x5004]), b"\xde\xad\xbe\xef")


class ResidueTest(unittest.TestCase):
    def test_an_image_still_carrying_a_port_access_is_reported(self) -> None:
        image = bytearray(0x10000)
        image[0x100:0x104] = sites.STA_PORT

        left = patch.residue(bytes(image))

        self.assertEqual(left[sites.KIND_WRITE], 1)

    def test_an_image_with_nothing_left_reports_nothing(self) -> None:
        self.assertEqual(patch.residue(bytes(0x10000)), {})


class SyntheticImageTest(unittest.TestCase):
    """The whole pass over an image, on one built here rather than on a cartridge."""

    def _image(self) -> Any:
        image = bytearray(0x10000)
        image[0x1000 : 0x1000 + len(sites.STA_PORT)] = sites.STA_PORT
        image[0x2000 : 0x2000 + len(sites.LDA_PORT)] = sites.LDA_PORT
        return bytes(image)

    def _symbols(self) -> Any:
        return patch.resolve(patch.read_symbols(SYMBOLS))

    def test_the_first_write_is_taken_as_the_boot_write_when_none_is_named(self) -> None:
        patched = patch.apply(self._image(), self._symbols())

        self.assertNotEqual(patched[0x1000:0x1004], sites.STA_PORT)

    def test_every_byte_the_patch_may_touch_is_declared(self) -> None:
        found = patch.regions(self._image())

        self.assertIn(0x1000, found)
        self.assertIn(0x2000, found)

    def test_a_call_to_a_trampoline_is_declared_too(self) -> None:
        image = bytearray(0x100000)
        at = (sites.TRAMPOLINE_BANK & 0x7F) * sites.BANK_SIZE + 0x40
        image[at : at + 3] = sites.call_to(next(iter(sites.TRAMPOLINES)))

        found = patch.regions(bytes(image))

        self.assertIn(at, found)

    def test_and_nothing_outside_a_site_is_declared(self) -> None:
        self.assertNotIn(0x3000, patch.regions(self._image()))

    def test_an_image_with_no_write_at_all_still_patches(self) -> None:
        image = bytearray(0x10000)
        image[0x2000 : 0x2000 + len(sites.LDA_PORT)] = sites.LDA_PORT

        patched = patch.apply(bytes(image), self._symbols())

        self.assertNotEqual(patched[0x2000:0x2004], sites.LDA_PORT)


if __name__ == "__main__":
    unittest.main(verbosity=2)
