"""Drive the routines across the whole input space, not only what a tour asked.

Replaying recorded traffic proves the routines answer what the cartridge asked
for. It says nothing about what they would answer to a request the tours never
made, and the tours make a small fraction of what the six commands accept: a
merge takes any length from 1 to 255 against any of sixteen transparent colours,
and a tour visits a handful of those combinations.

This generates cases from a seed across the declared space, including the edges
the game never reaches, takes the expected answers from the model that reproduced
every byte of the recorded runs, and drives them through the same cartridge, so
the comparison still happens on the processor rather than in Python.

Cases are generated by writing to the model and watching it, rather than by
duplicating its rules here. The model decides how many payload bytes a command
takes and how many it gives back, so a case cannot disagree with it about the
shape of a command while agreeing about the contents.

What a disagreement means needs saying, because the first version of this said
the wrong thing loudly. Its expectations come from the model, and the model is
not the cartridge: measured against the cartridge's own recorded answers, it
puts a byte in front of every tile result and leaves the exchange after a sync
unanswerable. One of either early in a run put every later read out of step, so
a run reported 38,380 wrong bytes of 39,375 and every one of them was the
oracle's. Both are now measured before anything is generated, and a command the
oracle fails is named and left out rather than counted against the routines.

Past that, a disagreement here is a disagreement between two things, and which
of them is wrong is a separate question. Where the recordings reach, they settle
it, and the routines reproduce every byte of them. Where they do not reach, the
two known cases are written up in OPEN-QUESTIONS.md rather than filed against
either side.
"""

import importlib.util
import random
import sys
from collections import namedtuple
from collections.abc import Callable
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent


def _load_tool(name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / f"{name}.py")
    assert spec is not None and spec.loader is not None, "no loader for that path"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


sys.path.insert(0, str(ROOT))
import hardware  # noqa: E402

hardware.install()

import snesdsp  # noqa: E402

replay = _load_tool("replay")
protocol = _load_tool("protocol")

PART = "dsp2"
"""The part this cartridge carries, and the microcode an expected answer comes from."""


def chip(build: Any = None) -> Any:
    """One DSP-2, running the part's own microcode rather than a description of it."""
    return (build or snesdsp.Chip)(PART)


def why_not(model: Any = None) -> Any:
    """Why cases cannot be built here, or nothing when they can."""
    return (model or snesdsp).why_not()


TILE = 0x01
TRANSPARENT = 0x03
MERGE = 0x05
MIRROR = 0x06
MULTIPLY = 0x09
SCALE = 0x0D
SYNC = 0x0F

COMMANDS = (TILE, TRANSPARENT, MERGE, MIRROR, MULTIPLY, SCALE, SYNC)

UNKNOWN = 0x100
"""Stands for any byte the chip does not recognise.

The reference sends every one of them down the same path as a sync: nothing
consumed, nothing produced, and the read cursor rewound. A generator that only
sends the seven it knows never walks that path, and the cartridge sends nothing
else, so nothing else would ever check it.
"""

UNRECOGNISED = tuple(value for value in range(256) if value not in COMMANDS)

WEIGHTS = {
    TILE: 12,
    TRANSPARENT: 8,
    MERGE: 40,
    MIRROR: 10,
    MULTIPLY: 10,
    SCALE: 10,
    SYNC: 4,
    UNKNOWN: 4,
}

EDGE_LENGTHS = (1, 2, 3, 4, 15, 16, 17, 127, 128, 254, 255)

Case = namedtuple("Case", "command lengths written expected")


def _length(rng: Any) -> int:
    if rng.random() < 0.4:
        chosen: int = rng.choice(EDGE_LENGTHS)
        return chosen
    drawn: int = rng.randrange(1, 256)
    return drawn


def _lengths_for(command: int, rng: Any) -> tuple[int, ...]:
    if command == UNKNOWN:
        return ()
    if command in (MERGE, MIRROR):
        return (_length(rng),)
    if command == SCALE:
        return (_length(rng), _length(rng))
    return ()


COLOURS = 16
"""How many transparent colours there are, which is how many a nibble holds.

The payload of every other command is pixel data and any byte of it is a fair
question. This one names a colour, and a colour is four bits. Drawn from the
whole byte instead, more than nine cases in ten set one that cannot exist, and
every merge after such a case compares two guesses about undefined behaviour
rather than two answers. Across four thousand recorded exchanges the cartridge
sets one colour, and it is below sixteen.
"""

OPENING_COLOUR = 0
"""The colour a run opens with, so nothing merges before one is in force.

A merge reads a pair of tables that the transparent command builds. Before any
has run, the model reads whatever its memory holds and the cartridge reads
whatever work RAM was filled with, and the two disagree for a reason that is
neither side's. The cartridge sets a colour before it merges; a generated run
that did not was asking a question with no answer.
"""


def build_cases(seed: int, count: int, only: Any = None, build: Any = chip) -> list[Any]:
    """Cases from a seed, with the model deciding every shape and every answer.

    `only` restricts the commands generated, which is how a disagreement gets
    narrowed to the command that causes it. The opening colour is set whatever
    it says, because it is what makes the rest of the run mean anything.

    A result is sometimes read only in part, because the chip rewinds a partly
    read result when the next command produces nothing and the cartridge never
    does that, so no recording exercises it.
    """
    rng = random.Random(seed)
    part = build()
    shape = protocol.Shape()
    chosen_commands = (*COMMANDS, UNKNOWN) if only is None else tuple(only)
    population = [command for command in chosen_commands for _ in range(WEIGHTS[command])]

    cases: list[Any] = []
    for step in range(count + 1):
        chosen = TRANSPARENT if step == 0 else rng.choice(population)
        command = rng.choice(UNRECOGNISED) if chosen == UNKNOWN else chosen
        lengths = _lengths_for(chosen, rng)

        written = bytearray([command, *lengths])
        for byte in written:
            part.write(byte)
            shape.wrote(byte)

        while shape.expecting_input:
            if command == TRANSPARENT:
                byte = OPENING_COLOUR if step == 0 else rng.randrange(COLOURS)
            else:
                byte = rng.randrange(256)
            written.append(byte)
            part.write(byte)
            shape.wrote(byte)

        pending: int = shape.produced
        wanted: int = pending
        if pending and rng.random() < 0.25:
            wanted = rng.randrange(0, pending)
        collected = bytearray()
        for _ in range(wanted):
            collected.append(part.read())
            shape.was_read()
        cases.append(Case(command, lengths, bytes(written), bytes(collected)))
    return cases


def runs_for(cases: Any) -> list[Any]:
    """The feed and check runs a list of cases becomes."""
    runs: list[Any] = []
    for case in cases:
        runs.append((replay.KIND_WRITE, case.written))
        if case.expected:
            runs.append((replay.KIND_READ, case.expected))
    return runs


NAMES = {
    TILE: "tile",
    TRANSPARENT: "transparent",
    MERGE: "merge",
    MIRROR: "mirror",
    MULTIPLY: "multiply",
    SCALE: "scale",
    SYNC: "sync",
}

BYTE_FOR = {name: command for command, name in NAMES.items()}

CALIBRATION_TRACE = ROOT / "build" / "trace-s1.bin"
"""What the oracle is measured against: the answers the cartridge's chip gave."""

WITNESS = "mirror"
"""The command a calibration asks again after the one it is checking.

Two ways of being wrong look nothing alike from the outside. A command the
model computes wrongly shows up in its own answer. A command that leaves the
model owing a byte the cartridge never took answers correctly itself and puts
every later read one out of step, so it is only visible in the next exchange.
Measured against this cartridge's own recording, both happen: the model answers
a tile one byte early, and both a tile and a sync leave the next exchange
unanswerable.

Mirror is the witness because it reproduces on its own, reproduces after
itself, and depends on nothing an earlier command set.
"""

Reading = namedtuple("Reading", "answered kept_up")


def answered(part: Any, transaction: Any) -> bool:
    """One recorded exchange fed to the oracle, against what the cartridge got back."""
    for byte in (
        bytes([transaction.command]) + bytes(transaction.lengths) + bytes(transaction.parameters)
    ):
        part.write(byte)
    given = bytes(part.read() for _ in range(len(transaction.output)))
    return given == bytes(transaction.output)


def sample(transactions: Any, wanted: Any = None) -> Any:
    """One recorded exchange per named command, and the transparent colour before them.

    The colour travels with them because a merge answers according to one a
    previous command set, and a merge measured without it disagrees for a reason
    that belongs to the sampling rather than to either side.
    """
    wanted = tuple(NAMES.values()) if wanted is None else tuple(wanted)
    found: dict[str, Any] = {}
    colour = None
    for transaction in transactions:
        if not transaction.complete:
            continue
        if transaction.name == NAMES[TRANSPARENT] and colour is None:
            colour = transaction
        if transaction.name in wanted and transaction.name not in found:
            found[transaction.name] = transaction
        if len(found) == len(wanted) and colour is not None:
            break
    return colour, found


def calibrate(colour: Any, witness: Any, subjects: Any, build: Any = chip) -> dict[str, Any]:
    """Which commands the oracle can be trusted for, measured against the cartridge.

    Each subject gets a part of its own, so one command the model gets wrong
    cannot condemn the rest, and each is asked with the witness before and after
    it. The one before establishes that this part started sound; the one after
    is the only thing that catches a command which answers correctly and breaks
    what follows.
    """
    verdicts: dict[str, Any] = {}
    for name, transaction in subjects.items():
        part = build()
        if colour is not None:
            answered(part, colour)
        answered(part, witness)
        verdicts[name] = Reading(answered(part, transaction), answered(part, witness))
    return verdicts


def trusted(readings: Any) -> tuple[int, ...]:
    """The command bytes a run may generate, given what the calibration found.

    An unrecognised byte goes the way the sync goes. The reference sends every
    one of them down the same path, so a sync the oracle cannot be trusted for
    is a byte it cannot be trusted for either, and there is nothing to measure
    that separately with: neither produces output to compare.
    """
    sound = {name for name, one in readings.items() if one.answered and one.kept_up}
    found = [BYTE_FOR[name] for name in sound if name in BYTE_FOR]
    if NAMES[SYNC] in sound:
        found.append(UNKNOWN)
    return tuple(sorted(found))


def oracle(
    trace: Any = None,
    build: Any = chip,
    transactions: Any = None,
) -> dict[str, Any] | None:
    """The calibration, or nothing when there is no recording to calibrate against."""
    if transactions is None:
        trace = CALIBRATION_TRACE if trace is None else Path(trace)
        if not trace.exists():
            return None
        import dsptrace

        transactions = dsptrace.transactions(dsptrace.records(trace))

    colour, found = sample(transactions)
    if WITNESS not in found:
        return None
    return calibrate(colour, found[WITNESS], found, build)


def walk(
    build: Any,
    skeleton: Any,
    batches: Any,
    run_batch: Any,
    say: Callable[[str], None],
    clock: Any,
) -> Any:
    """Every batch through the cartridge, or nothing when one does not finish.

    A batch that stops early has left the routines somewhere nobody can describe,
    so the numbers after it would be measured against a machine in an unknown
    state. The run ends there rather than reporting them.
    """
    walked = compared = wrong = 0
    failures: list[Any] = []
    for number, batch in enumerate(batches):
        started = clock()
        script, found = run_batch(build, skeleton, batch)
        if not found["finished"]:
            say(f"  batch {number} did not finish, {found['compared']} checked")
            return None
        walked += found["transactions"]
        compared += found["compared"]
        wrong += found["wrong"]
        if found["wrong"]:
            failures.append((number, found))
        say(
            f"    batch {number:3d}: {len(script):8d} bytes of script, "
            f"{found['compared']:9d} checked, {found['wrong']:6d} wrong, "
            f"{clock() - started:5.1f}s"
        )
    return walked, compared, wrong, failures


def summary_lines(cases: Any, walked: Any, compared: int, wrong: int, failures: Any) -> list[str]:
    """What a run found, in the order somebody reading it wants it."""
    per_command: dict[int, int] = {}
    for case in cases:
        per_command[case.command] = per_command.get(case.command, 0) + 1

    names = dict(NAMES)
    for command in sorted(per_command):
        names.setdefault(command, f"unknown ${command:02X}")

    lines = ["", "  cases by command:"]
    lines.extend(f"    {names[command]:12s} {per_command.get(command, 0)}" for command in COMMANDS)
    strange = sum(count for command, count in per_command.items() if command not in COMMANDS)
    lines.append(f"    {'unrecognised':12s} {strange}")
    lines.append("")
    lines.append(f"  runs walked   {walked}")
    lines.append(f"  bytes checked {compared}")
    lines.append(f"  bytes wrong   {wrong}")
    lines.extend(
        f"    batch {number}: first at byte {found['first']}, "
        f"part ${found['expected']:02X}, routines ${found['returned']:02X}"
        for number, found in failures[:5]
    )
    return lines


def main(
    argv: list[str],
    refuses: Any = why_not,
    assemble: Any = replay.assemble,
    run_batch: Any = replay.run_batch,
    generate: Any = build_cases,
    say: Callable[[str], None] = print,
    clock: Any = None,
    checked: Any = None,
) -> int:
    """Cases from a seed, driven through the cartridge and checked on the processor."""
    import time

    clock = time.time if clock is None else clock
    checked = oracle if checked is None else checked

    seed = int(argv[0]) if argv else 1
    count = int(argv[1]) if len(argv) > 1 else 20000
    only = [int(name, 0) for name in argv[2:]] or None

    reason = refuses()
    if reason:
        say(f"  nothing to build: {reason}")
        return 2

    readings = checked()
    if readings is None:
        say("  the oracle is unchecked: no recording here to measure it against, and")
        say("  a run against an unmeasured oracle reports its faults as the routines'")
        return 2

    for name, one in sorted(readings.items()):
        if one.answered and one.kept_up:
            continue
        fault = (
            "answers what the cartridge did not"
            if not one.answered
            else "answers correctly and leaves the next exchange unanswerable"
        )
        say(f"  {name} is left out: against this recording the model {fault}")

    allowed = trusted(readings)
    wanted = [one for one in (only or allowed) if one in allowed]
    if not wanted:
        say("  nothing left to generate, so there is nothing this run could report")
        return 2

    build = ROOT / "build"
    skeleton = assemble(ROOT, build)
    say(f"  cartridge built, {len(skeleton)} bytes")

    cases = generate(seed, count, wanted)
    runs = runs_for(cases)
    expected = sum(len(case.expected) for case in cases)
    say(f"  seed {seed}, {len(cases)} cases, {expected} bytes the part gave back")

    room = replay.capacity(replay.IMAGE_BYTES) - replay.MAX_OVERSHOOT
    found = walk(build, skeleton, replay.batches_of(runs, room), run_batch, say, clock)
    if found is None:
        return 1

    walked, compared, wrong, failures = found
    for line in summary_lines(cases, walked, compared, wrong, failures):
        say(line)
    return 0 if wrong == 0 else 1


if __name__ == "__main__":
    sys.stdout.reconfigure(line_buffering=True)  # type: ignore[union-attr]
    raise SystemExit(main(sys.argv[1:]))
