"""Drive the routines across the whole input space, not only what a tour asked.

Replaying recorded traffic proves the routines answer what the cartridge asked
for. It says nothing about what they would answer to a request the tours never
made, and the tours make a small fraction of what the six commands accept: a
merge takes any length from 1 to 255 against any of sixteen transparent colours,
and a tour visits a handful of those combinations.

This generates cases from a seed across the declared space, including the edges
the game never reaches, takes the expected answers from the model that reproduced
every byte of the recorded runs, and drives them through the same cartridge, so
the comparison still happens on the processor rather than in Python.

Cases are generated by writing to the model and watching it, rather than by
duplicating its rules here. The model decides how many payload bytes a command
takes and how many it gives back, so a case cannot disagree with it about the
shape of a command while agreeing about the contents.
"""

import importlib.util
import random
from collections import namedtuple
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_tool(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


dsp2 = _load("dsp2")
replay = _load_tool("replay")

TILE = 0x01
TRANSPARENT = 0x03
MERGE = 0x05
MIRROR = 0x06
MULTIPLY = 0x09
SCALE = 0x0D
SYNC = 0x0F

COMMANDS = (TILE, TRANSPARENT, MERGE, MIRROR, MULTIPLY, SCALE, SYNC)

WEIGHTS = {
    TILE: 12,
    TRANSPARENT: 8,
    MERGE: 40,
    MIRROR: 10,
    MULTIPLY: 10,
    SCALE: 10,
    SYNC: 4,
}

EDGE_LENGTHS = (1, 2, 3, 4, 15, 16, 17, 127, 128, 254, 255)

Case = namedtuple("Case", "command lengths written expected")


def _length(rng):
    if rng.random() < 0.4:
        return rng.choice(EDGE_LENGTHS)
    return rng.randrange(1, 256)


def _lengths_for(command, rng):
    if command in (MERGE, MIRROR):
        return (_length(rng),)
    if command == SCALE:
        return (_length(rng), _length(rng))
    return ()


def build_cases(seed, count, only=None):
    """Cases from a seed, with the model deciding every shape and every answer.

    `only` restricts the commands generated, which is how a disagreement gets
    narrowed to the command that causes it.
    """
    rng = random.Random(seed)
    chip = dsp2.Chip()
    wanted = COMMANDS if only is None else tuple(only)
    population = [command for command in wanted for _ in range(WEIGHTS[command])]

    cases = []
    for _ in range(count):
        command = rng.choice(population)
        lengths = _lengths_for(command, rng)

        written = bytearray([command, *lengths])
        for byte in written:
            chip.write(byte)

        while chip.command is not None:
            byte = rng.randrange(256)
            written.append(byte)
            chip.write(byte)

        expected = bytes(chip.read() for _ in range(chip.pending_output))
        cases.append(Case(command, lengths, bytes(written), expected))
    return cases


def runs_for(cases):
    """The feed and check runs a list of cases becomes."""
    runs = []
    for case in cases:
        runs.append((replay.KIND_WRITE, case.written))
        if case.expected:
            runs.append((replay.KIND_READ, case.expected))
    return runs


def main(argv):
    import time

    seed = int(argv[0]) if argv else 1
    count = int(argv[1]) if len(argv) > 1 else 20000
    only = [int(name, 0) for name in argv[2:]] or None

    build = ROOT / "build"
    skeleton = replay.assemble(ROOT, build)
    print(f"  cartridge built, {len(skeleton)} bytes")

    cases = build_cases(seed, count, only)
    runs = runs_for(cases)
    expected = sum(len(case.expected) for case in cases)
    print(f"  seed {seed}, {len(cases)} cases, {expected} bytes the model expects back")

    room = replay.capacity(replay.IMAGE_BYTES) - 16
    walked = compared = wrong = 0
    failures = []
    for number, batch in enumerate(replay.batches_of(runs, room)):
        started = time.time()
        script, found = replay.run_batch(build, skeleton, batch)
        if not found["finished"]:
            print(f"  batch {number} did not finish, {found['compared']} checked")
            return 1
        walked += found["transactions"]
        compared += found["compared"]
        wrong += found["wrong"]
        if found["wrong"]:
            failures.append((number, found))
        print(
            f"    batch {number:3d}: {len(script):8d} bytes of script, "
            f"{found['compared']:9d} checked, {found['wrong']:6d} wrong, "
            f"{time.time() - started:5.1f}s"
        )

    per_command = {}
    for case in cases:
        per_command[case.command] = per_command.get(case.command, 0) + 1
    names = {
        TILE: "tile",
        TRANSPARENT: "transparent",
        MERGE: "merge",
        MIRROR: "mirror",
        MULTIPLY: "multiply",
        SCALE: "scale",
        SYNC: "sync",
    }
    print("\n  cases by command:")
    for command in COMMANDS:
        print(f"    {names[command]:12s} {per_command.get(command, 0)}")

    print(f"\n  runs walked   {walked}")
    print(f"  bytes checked {compared}")
    print(f"  bytes wrong   {wrong}")
    for number, found in failures[:5]:
        print(
            f"    batch {number}: first at byte {found['first']}, "
            f"model ${found['expected']:02X}, routines ${found['returned']:02X}"
        )
    return 0 if wrong == 0 else 1


if __name__ == "__main__":
    import sys

    raise SystemExit(main(sys.argv[1:]))
