"""Drive the routines across the whole input space, not only what a tour asked.

Replaying recorded traffic proves the routines answer what the cartridge asked
for. It says nothing about what they would answer to a request the tours never
made, and the tours make a small fraction of what the six commands accept: a
merge takes any length from 1 to 255 against any of sixteen transparent colours,
and a tour visits a handful of those combinations.

This generates cases from a seed across the declared space, including the edges
the game never reaches, takes the expected answers from the model that reproduced
every byte of the recorded runs, and drives them through the same cartridge, so
the comparison still happens on the processor rather than in Python.

Cases are generated by writing to the model and watching it, rather than by
duplicating its rules here. The model decides how many payload bytes a command
takes and how many it gives back, so a case cannot disagree with it about the
shape of a command while agreeing about the contents.
"""

import importlib.util
import random
import sys
from collections import namedtuple
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _load_tool(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


sys.path.insert(0, str(ROOT))
import hardware  # noqa: E402

hardware.install()

import snesdsp  # noqa: E402

replay = _load_tool("replay")
protocol = _load_tool("protocol")

PART = "dsp2"
"""The part this cartridge carries, and the microcode an expected answer comes from."""


def chip(build=None):
    """One DSP-2, running the part's own microcode rather than a description of it."""
    return (build or snesdsp.Chip)(PART)


def why_not(model=None):
    """Why cases cannot be built here, or nothing when they can."""
    return (model or snesdsp).why_not()


TILE = 0x01
TRANSPARENT = 0x03
MERGE = 0x05
MIRROR = 0x06
MULTIPLY = 0x09
SCALE = 0x0D
SYNC = 0x0F

COMMANDS = (TILE, TRANSPARENT, MERGE, MIRROR, MULTIPLY, SCALE, SYNC)

UNKNOWN = 0x100
"""Stands for any byte the chip does not recognise.

The reference sends every one of them down the same path as a sync: nothing
consumed, nothing produced, and the read cursor rewound. A generator that only
sends the seven it knows never walks that path, and the cartridge sends nothing
else, so nothing else would ever check it.
"""

UNRECOGNISED = tuple(value for value in range(256) if value not in COMMANDS)

WEIGHTS = {
    TILE: 12,
    TRANSPARENT: 8,
    MERGE: 40,
    MIRROR: 10,
    MULTIPLY: 10,
    SCALE: 10,
    SYNC: 4,
    UNKNOWN: 4,
}

EDGE_LENGTHS = (1, 2, 3, 4, 15, 16, 17, 127, 128, 254, 255)

Case = namedtuple("Case", "command lengths written expected")


def _length(rng):
    if rng.random() < 0.4:
        return rng.choice(EDGE_LENGTHS)
    return rng.randrange(1, 256)


def _lengths_for(command, rng):
    if command == UNKNOWN:
        return ()
    if command in (MERGE, MIRROR):
        return (_length(rng),)
    if command == SCALE:
        return (_length(rng), _length(rng))
    return ()


def build_cases(seed, count, only=None, build=chip):
    """Cases from a seed, with the model deciding every shape and every answer.

    `only` restricts the commands generated, which is how a disagreement gets
    narrowed to the command that causes it.

    A result is sometimes read only in part, because the chip rewinds a partly
    read result when the next command produces nothing and the cartridge never
    does that, so no recording exercises it.
    """
    rng = random.Random(seed)
    part = build()
    shape = protocol.Shape()
    wanted = (*COMMANDS, UNKNOWN) if only is None else tuple(only)
    population = [command for command in wanted for _ in range(WEIGHTS[command])]

    cases = []
    for _ in range(count):
        chosen = rng.choice(population)
        command = rng.choice(UNRECOGNISED) if chosen == UNKNOWN else chosen
        lengths = _lengths_for(chosen, rng)

        written = bytearray([command, *lengths])
        for byte in written:
            part.write(byte)
            shape.wrote(byte)

        while shape.expecting_input:
            byte = rng.randrange(256)
            written.append(byte)
            part.write(byte)
            shape.wrote(byte)

        pending = shape.produced
        wanted = pending
        if pending and rng.random() < 0.25:
            wanted = rng.randrange(0, pending)
        expected = bytearray()
        for _ in range(wanted):
            expected.append(part.read())
            shape.was_read()
        expected = bytes(expected)
        cases.append(Case(command, lengths, bytes(written), expected))
    return cases


def runs_for(cases):
    """The feed and check runs a list of cases becomes."""
    runs = []
    for case in cases:
        runs.append((replay.KIND_WRITE, case.written))
        if case.expected:
            runs.append((replay.KIND_READ, case.expected))
    return runs


NAMES = {
    TILE: "tile",
    TRANSPARENT: "transparent",
    MERGE: "merge",
    MIRROR: "mirror",
    MULTIPLY: "multiply",
    SCALE: "scale",
    SYNC: "sync",
}


def walk(build, skeleton, batches, run_batch, say, clock):
    """Every batch through the cartridge, or nothing when one does not finish.

    A batch that stops early has left the routines somewhere nobody can describe,
    so the numbers after it would be measured against a machine in an unknown
    state. The run ends there rather than reporting them.
    """
    walked = compared = wrong = 0
    failures = []
    for number, batch in enumerate(batches):
        started = clock()
        script, found = run_batch(build, skeleton, batch)
        if not found["finished"]:
            say(f"  batch {number} did not finish, {found['compared']} checked")
            return None
        walked += found["transactions"]
        compared += found["compared"]
        wrong += found["wrong"]
        if found["wrong"]:
            failures.append((number, found))
        say(
            f"    batch {number:3d}: {len(script):8d} bytes of script, "
            f"{found['compared']:9d} checked, {found['wrong']:6d} wrong, "
            f"{clock() - started:5.1f}s"
        )
    return walked, compared, wrong, failures


def summary_lines(cases, walked, compared, wrong, failures):
    """What a run found, in the order somebody reading it wants it."""
    per_command = {}
    for case in cases:
        per_command[case.command] = per_command.get(case.command, 0) + 1

    names = dict(NAMES)
    for command in sorted(per_command):
        names.setdefault(command, f"unknown ${command:02X}")

    lines = ["", "  cases by command:"]
    lines.extend(f"    {names[command]:12s} {per_command.get(command, 0)}" for command in COMMANDS)
    strange = sum(count for command, count in per_command.items() if command not in COMMANDS)
    lines.append(f"    {'unrecognised':12s} {strange}")
    lines.append("")
    lines.append(f"  runs walked   {walked}")
    lines.append(f"  bytes checked {compared}")
    lines.append(f"  bytes wrong   {wrong}")
    lines.extend(
        f"    batch {number}: first at byte {found['first']}, "
        f"part ${found['expected']:02X}, routines ${found['returned']:02X}"
        for number, found in failures[:5]
    )
    return lines


def main(
    argv,
    refuses=why_not,
    assemble=replay.assemble,
    run_batch=replay.run_batch,
    generate=build_cases,
    say=print,
    clock=None,
):
    """Cases from a seed, driven through the cartridge and checked on the processor."""
    import time

    clock = time.time if clock is None else clock

    seed = int(argv[0]) if argv else 1
    count = int(argv[1]) if len(argv) > 1 else 20000
    only = [int(name, 0) for name in argv[2:]] or None

    reason = refuses()
    if reason:
        say(f"  nothing to build: {reason}")
        return 2

    build = ROOT / "build"
    skeleton = assemble(ROOT, build)
    say(f"  cartridge built, {len(skeleton)} bytes")

    cases = generate(seed, count, only)
    runs = runs_for(cases)
    expected = sum(len(case.expected) for case in cases)
    say(f"  seed {seed}, {len(cases)} cases, {expected} bytes the part gave back")

    room = replay.capacity(replay.IMAGE_BYTES) - replay.MAX_OVERSHOOT
    found = walk(build, skeleton, replay.batches_of(runs, room), run_batch, say, clock)
    if found is None:
        return 1

    walked, compared, wrong, failures = found
    for line in summary_lines(cases, walked, compared, wrong, failures):
        say(line)
    return 0 if wrong == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
